name: OpenMrs Setup
description: 'OpenMRS Setup'
runs:
  using: composite
  steps:
    - name: Run OpenMRS
      shell: bash
      run: |
        docker compose up -d --wait
        curl -I http://localhost/openmrs/spa

    - name: Run App Setup test
      shell: bash
      run: pytest -m app_setup --video retain-on-failure

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-artifacts
        path: test-results/
        retention-days: 1