repos:
  - repo: local
    hooks:
      - id: ruff-unused-imports
        name: ruff-unused-imports
        entry: ruff
        args: [check, --fix, --select, F401]
        language: python
        additional_dependencies: [ruff]
        types: [python]
      - id: ruff
        name: ruff
        entry: ruff
        args: [check]
        language: python
        additional_dependencies: [ruff]
        types: [python]
      - id: isort
        name: isort
        entry: isort
        language: python
        additional_dependencies: [isort]
        types: [python]
      - id: yapf
        name: yapf
        entry: yapf
        args: [--style, .style.yapf, --in-place]
        language: python
        additional_dependencies: [yapf]
        types: [python]
