[pytest]

pythonpath = .

#addopts = --browser chromium --browser firefox --browser webkit

markers =
    api: API autotests
    ui: UI autotests
    debug: Debug
    check_visit_persisted: verify visit persisted by fetching full representation
    check_visit_not_created: verify visit was NOT created
    check_visit_deleted: verify visit was deleted
    check_visit_updated: verify visit was updated (stopDatetime) by GET /visit/{uuid}
    user_session(count, auth_index): Marker for tests with user login
    admin_session: For tests with admin login
    browsers(names): Tests for only current browsers (chromium|firefox|webkit)
    check_all_patients_change: verify patients count change in DB.patient table
    check_visit_created_in_db(expected_delta, patient_source): verify visits count delta in DB.visit for patient(s)
    check_visit_ended_in_db(patient_fixture): verify active visit got date_stopped in DB after test
    check_visit_not_ended_in_db(visit_fixture): verify visit date_stopped is still NULL after test