[pytest]

pythonpath = .

markers =
    api: API autotests
    debug: Debug
    check_visit_persisted: verify visit persisted by fetching full representation
    check_visit_not_created: verify visit was NOT created
    check_visit_deleted: verify visit was deleted
    check_visit_updated: verify visit was updated (stopDatetime) by GET /visit/{uuid}