[DEFAULT]
server = http://localhost/openmrs/ws/rest
api_version = /v1
default_seed = 110

# UI
UI_BASE_SPA_URL = http://localhost/openmrs/spa
UI_BASE_URL = http://localhost/openmrs
HEADLESS=false
BROWSER_WIDTH = 1920
BROWSER_HEIGHT = 1080

# Database
DB_HOST=localhost
DB_PORT=3306
DB_NAME=openmrs
DB_USERNAME=openmrs
DB_PASSWORD=openmrs

ADMIN_USERNAME = admin
ADMIN_PASSWORD = Admin123
ADMIN_ROLE = ADMIN