name: Run tests
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright Browsers
      run: playwright install --with-deps

    - name: OpenMRS Setup
      uses: ./.github/actions/openmrs-setup

    - name: Run API tests
      run: pytest -n 2 -m api


    - name: Send Telegram notification
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          STATUS="✅ CI SUCCESS"
          RESULT="success"
        else
          STATUS="❌ CI FAILED"
          RESULT="failure"
        fi

        MESSAGE="$STATUS

        *Repository:" ${{ github.repository }}
        🌿 *Branch:* ${{ github.ref_name }}
        👤 *Author:* ${{ github.actor }}

        📋 *Results:*
        • API Tests: $RESULT
        • UI Tests: $RESULT

        *Pipeline:* [ Run #${{ github.run_number }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
      
          curl -s -X POST "https://api.telegram.org/bot${ { secrets.TELEGRAM_BOT_TOKEN } }/sendMessage" \
          -d chat_id="${ { secrets.TELEGRAM_CHAT_ID } }" \
              -d text="$MESSAGE" \
          -d parse_mode="Markdown"